
variables:
  PIPENV_VENV_IN_PROJECT: "true"

image: "python:3.7-buster"

basic_tests:
  before_script:
    - apt update -qy
    - apt install -y poppler-utils imagemagick libmagickcore-6.q16-6-extra ghostscript netpbm gsfonts wget
    - pip3 install pipenv
    - pipenv --version
    - ./fetch_models.sh
  script:
    - cp example.env .env
    - pipenv install --dev --deploy
    - pipenv run pytest --cov
    # Just errors
    - pipenv run pylint -E pdf_trio tests/*.py
